package ca.markw.positivepracticewaterman;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mark
 */
public class PositivePracticeWaterman extends javax.swing.JFrame {
	/**
	 * Creates new form WatermanFirstProgram
	 */
	private final java.util.Random RNG = new java.util.Random();
	private final String[] QUOTES = {
		"Looking? Found someone you have, eh?",
		"No! Try not. Do. Or do not. There is no try.",
		"Patience you must have, my young Padawan.",
		"If no mistake have you made, yet losing you are, a different game you should play.",
		"When you look at the dark side, careful you must be. For the dark side looks back.",
		"Size matters not. Look at me. Judge me by my size, do you? Hmm? \n"
		+ "And well you should not. For my ally is the Force, and a powerful ally it is.",
		"Great warrior. Hmm. Wars not make one great.",
		"You must unlearn what you have learned.",
		"When 900 years old you reach, look this good you will not."
	};
	public PositivePracticeWaterman() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUI_title = new javax.swing.JLabel();
        GUI_generate = new javax.swing.JButton();
        GUI_average_label = new javax.swing.JLabel();
        GUI_quote = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        GUI_title.setText("Positive Practice!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(GUI_title, gridBagConstraints);

        GUI_generate.setText("Generate Quote");
        GUI_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_generateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_generate, gridBagConstraints);

        GUI_average_label.setText("Click The Generate Quote button in order to be inspired!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_average_label, gridBagConstraints);

        GUI_quote.setEditable(false);
        GUI_quote.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        GUI_quote.setColumns(48);
        GUI_quote.setRows(2);
        GUI_quote.setText("Inspiring Quote");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(GUI_quote, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GUI_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_generateActionPerformed
		GUI_quote.setText("“" + QUOTES[RNG.nextInt(9)] + "” — Yoda");
    }//GEN-LAST:event_GUI_generateActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PositivePracticeWaterman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PositivePracticeWaterman().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GUI_average_label;
    private javax.swing.JButton GUI_generate;
    private javax.swing.JTextArea GUI_quote;
    private javax.swing.JLabel GUI_title;
    // End of variables declaration//GEN-END:variables
}