package ca.markw.shopwaterman;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mark
 */
public class ShopWaterman extends javax.swing.JFrame {
	private final double[] costs = {2.15, 2.75, 3.35, 3.55, 4.20, 5.80};
	private final javax.swing.JSpinner[] items;
	private double subtotal;
	private double tax;
	private double total;
	/**
	 * Creates new form WatermanFirstProgram
	 */
	public ShopWaterman() {
		initComponents();
		items = new javax.swing.JSpinner[]{GUI_item1, GUI_item2, GUI_item3, GUI_item4, GUI_item5, GUI_item6};
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUI_title = new javax.swing.JLabel();
        GUI_item1_label = new javax.swing.JLabel();
        GUI_item1_value = new javax.swing.JLabel();
        GUI_item1 = new javax.swing.JSpinner();
        GUI_item2_label = new javax.swing.JLabel();
        GUI_item2_value = new javax.swing.JLabel();
        GUI_item2 = new javax.swing.JSpinner();
        GUI_item3_label = new javax.swing.JLabel();
        GUI_item3_value = new javax.swing.JLabel();
        GUI_item3 = new javax.swing.JSpinner();
        GUI_item4_label = new javax.swing.JLabel();
        GUI_item4_value = new javax.swing.JLabel();
        GUI_item4 = new javax.swing.JSpinner();
        GUI_item5_label = new javax.swing.JLabel();
        GUI_item5_value = new javax.swing.JLabel();
        GUI_item5 = new javax.swing.JSpinner();
        GUI_item6_label = new javax.swing.JLabel();
        GUI_item6_value = new javax.swing.JLabel();
        GUI_item6 = new javax.swing.JSpinner();
        GUI_calculate = new javax.swing.JButton();
        GUI_subtotal_label = new javax.swing.JLabel();
        GUI_subtotal = new javax.swing.JTextField();
        GUI_tax_label = new javax.swing.JLabel();
        GUI_tax_value = new javax.swing.JLabel();
        GUI_tax = new javax.swing.JTextField();
        GUI_total_label = new javax.swing.JLabel();
        GUI_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        GUI_title.setText("Chotchkies Restaurant");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(GUI_title, gridBagConstraints);

        GUI_item1_label.setText("Mixed Fruit:");
        GUI_item1_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GUI_item1_label.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item1_label, gridBagConstraints);

        GUI_item1_value.setText("$2.15");
        GUI_item1_value.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item1_value, gridBagConstraints);

        GUI_item1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        GUI_item1.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item1, gridBagConstraints);

        GUI_item2_label.setText("French Fries:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item2_label, gridBagConstraints);

        GUI_item2_value.setText("$2.75");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item2_value, gridBagConstraints);

        GUI_item2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item2, gridBagConstraints);

        GUI_item3_label.setText("Side Salad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item3_label, gridBagConstraints);

        GUI_item3_value.setText("$3.35");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item3_value, gridBagConstraints);

        GUI_item3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item3, gridBagConstraints);

        GUI_item4_label.setText("Hot Wings:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item4_label, gridBagConstraints);

        GUI_item4_value.setText("$3.55");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item4_value, gridBagConstraints);

        GUI_item4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item4, gridBagConstraints);

        GUI_item5_label.setText("Mozzarella Sticks:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item5_label, gridBagConstraints);

        GUI_item5_value.setText("$4.20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item5_value, gridBagConstraints);

        GUI_item5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item5, gridBagConstraints);

        GUI_item6_label.setText("Sampler Plate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item6_label, gridBagConstraints);

        GUI_item6_value.setText("$5.80");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item6_value, gridBagConstraints);

        GUI_item6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_item6, gridBagConstraints);

        GUI_calculate.setText("Calculate");
        GUI_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_calculateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_calculate, gridBagConstraints);

        GUI_subtotal_label.setText("Subtotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_subtotal_label, gridBagConstraints);

        GUI_subtotal.setEditable(false);
        GUI_subtotal.setText("Subtotal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_subtotal, gridBagConstraints);

        GUI_tax_label.setText("Tax:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_tax_label, gridBagConstraints);

        GUI_tax_value.setText("13%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_tax_value, gridBagConstraints);

        GUI_tax.setEditable(false);
        GUI_tax.setText("Tax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_tax, gridBagConstraints);

        GUI_total_label.setText("Grand Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_total_label, gridBagConstraints);

        GUI_total.setEditable(false);
        GUI_total.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_total, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GUI_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_calculateActionPerformed
		subtotal = 0;
		for (int i = 0; i < items.length; i++) {
			subtotal += costs[i] * (int) items[i].getValue();
		}
		tax = Math.floor(13d * subtotal)/100d;
		total = subtotal + tax;
		GUI_subtotal.setText( "" + subtotal);
		GUI_tax.setText( "" + tax);
		GUI_total.setText( "" + total);
    }//GEN-LAST:event_GUI_calculateActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ShopWaterman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShopWaterman().setVisible(true);
			}
		});
	}
// <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUI_calculate;
    private javax.swing.JSpinner GUI_item1;
    private javax.swing.JLabel GUI_item1_label;
    private javax.swing.JLabel GUI_item1_value;
    private javax.swing.JSpinner GUI_item2;
    private javax.swing.JLabel GUI_item2_label;
    private javax.swing.JLabel GUI_item2_value;
    private javax.swing.JSpinner GUI_item3;
    private javax.swing.JLabel GUI_item3_label;
    private javax.swing.JLabel GUI_item3_value;
    private javax.swing.JSpinner GUI_item4;
    private javax.swing.JLabel GUI_item4_label;
    private javax.swing.JLabel GUI_item4_value;
    private javax.swing.JSpinner GUI_item5;
    private javax.swing.JLabel GUI_item5_label;
    private javax.swing.JLabel GUI_item5_value;
    private javax.swing.JSpinner GUI_item6;
    private javax.swing.JLabel GUI_item6_label;
    private javax.swing.JLabel GUI_item6_value;
    private javax.swing.JTextField GUI_subtotal;
    private javax.swing.JLabel GUI_subtotal_label;
    private javax.swing.JTextField GUI_tax;
    private javax.swing.JLabel GUI_tax_label;
    private javax.swing.JLabel GUI_tax_value;
    private javax.swing.JLabel GUI_title;
    private javax.swing.JTextField GUI_total;
    private javax.swing.JLabel GUI_total_label;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
}