package ca.markw.averagewaterman;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mark
 */
public class AverageWaterman extends javax.swing.JFrame {

	private final javax.swing.JSpinner[] marks;
	private double acc;
	/**
	 * Creates new form WatermanFirstProgram
	 */
	public AverageWaterman() {
		initComponents();
		marks = new javax.swing.JSpinner[]{GUI_mark1, GUI_mark2, GUI_mark3, GUI_mark4};
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUI_title = new javax.swing.JLabel();
        GUI_mark1_label = new javax.swing.JLabel();
        GUI_mark1 = new javax.swing.JSpinner();
        GUI_mark2_label = new javax.swing.JLabel();
        GUI_mark2 = new javax.swing.JSpinner();
        GUI_mark3_label = new javax.swing.JLabel();
        GUI_mark3 = new javax.swing.JSpinner();
        GUI_mark4_label = new javax.swing.JLabel();
        GUI_mark4 = new javax.swing.JSpinner();
        GUI_calculate = new javax.swing.JButton();
        GUI_average_label = new javax.swing.JLabel();
        GUI_average = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        GUI_title.setText("Course Mark Average Calculator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(GUI_title, gridBagConstraints);

        GUI_mark1_label.setText("Course Mark 1:");
        GUI_mark1_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GUI_mark1_label.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark1_label, gridBagConstraints);

        GUI_mark1.setModel(new javax.swing.SpinnerNumberModel(50.0d, 0.0d, 100.0d, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark1, gridBagConstraints);

        GUI_mark2_label.setText("Course Mark 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark2_label, gridBagConstraints);

        GUI_mark2.setModel(new javax.swing.SpinnerNumberModel(50.0d, 0.0d, 100.0d, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark2, gridBagConstraints);

        GUI_mark3_label.setText("Course Mark 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark3_label, gridBagConstraints);

        GUI_mark3.setModel(new javax.swing.SpinnerNumberModel(50.0d, 0.0d, 100.0d, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark3, gridBagConstraints);

        GUI_mark4_label.setText("Course Mark 4:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark4_label, gridBagConstraints);

        GUI_mark4.setModel(new javax.swing.SpinnerNumberModel(50.0d, 0.0d, 100.0d, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_mark4, gridBagConstraints);

        GUI_calculate.setText("Calculate");
        GUI_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_calculateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_calculate, gridBagConstraints);

        GUI_average_label.setText("Course Average :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_average_label, gridBagConstraints);

        GUI_average.setEditable(false);
        GUI_average.setText("Average");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_average, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUI_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_calculateActionPerformed
		acc = 0;
		for (var mark : marks) {
			acc += (double) mark.getValue();
		}
		acc /= marks.length;
		acc = Math.round(10d*acc)*.1d;
		GUI_average.setText( "" + acc);
    }//GEN-LAST:event_GUI_calculateActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AverageWaterman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AverageWaterman().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GUI_average;
    private javax.swing.JLabel GUI_average_label;
    private javax.swing.JButton GUI_calculate;
    private javax.swing.JSpinner GUI_mark1;
    private javax.swing.JLabel GUI_mark1_label;
    private javax.swing.JSpinner GUI_mark2;
    private javax.swing.JLabel GUI_mark2_label;
    private javax.swing.JSpinner GUI_mark3;
    private javax.swing.JLabel GUI_mark3_label;
    private javax.swing.JSpinner GUI_mark4;
    private javax.swing.JLabel GUI_mark4_label;
    private javax.swing.JLabel GUI_title;
    // End of variables declaration//GEN-END:variables
}