package ca.markw.dicegamewaterman;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mark
 */
public class DiceGameWaterman extends javax.swing.JFrame {
	private final java.util.Random RNG = new java.util.Random();
	private final String[] DICETEXT = {"⚀","⚁","⚂","⚃","⚄","⚅"};
	private int guess = 1;
	private int dice = 0;
	private int rolls = 0;
	private int correct = 0;
	private int incorrect = 0;
	private double percentage = Double.NaN;
	private void GUI_roll_event(){
		guess = (int) GUI_guess.getValue();
		dice = RNG.nextInt(1, 7);
		rolls++;
		if(guess == dice){
			correct++;
		}else{
			incorrect++;
		}
		percentage = Math.round(10000 * correct / rolls) / 100;
		GUI_dice.setText(DICETEXT[dice - 1]);
		GUI_rolls.setText("" + rolls);
		GUI_correct.setText("" + correct);
		GUI_incorrect.setText("" + incorrect);
		GUI_percentage.setText("" + percentage);
	}
	/**
	 * Creates new form WatermanFirstProgram
	 */
	public DiceGameWaterman() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUI_title = new javax.swing.JLabel();
        GUI_guess_label = new javax.swing.JLabel();
        GUI_guess = new javax.swing.JSpinner();
        GUI_dice_label = new javax.swing.JLabel();
        GUI_dice = new javax.swing.JTextField();
        GUI_roll = new javax.swing.JButton();
        GUI_rolls_label = new javax.swing.JLabel();
        GUI_rolls = new javax.swing.JTextField();
        GUI_correct_label = new javax.swing.JLabel();
        GUI_correct = new javax.swing.JTextField();
        GUI_incorrect_label = new javax.swing.JLabel();
        GUI_incorrect = new javax.swing.JTextField();
        GUI_percentage_label = new javax.swing.JLabel();
        GUI_percentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        GUI_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GUI_title.setText("Super Dice Guessing Game");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(GUI_title, gridBagConstraints);

        GUI_guess_label.setText("Your guess");
        GUI_guess_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GUI_guess_label.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_guess_label, gridBagConstraints);

        GUI_guess.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_guess, gridBagConstraints);

        GUI_dice_label.setText("Dice roll");
        GUI_dice_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GUI_dice_label.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_dice_label, gridBagConstraints);

        GUI_dice.setEditable(false);
        GUI_dice.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_dice, gridBagConstraints);

        GUI_roll.setText("Roll");
        GUI_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_roll_event(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(GUI_roll, gridBagConstraints);

        GUI_rolls_label.setText("rolls");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_rolls_label, gridBagConstraints);

        GUI_rolls.setEditable(false);
        GUI_rolls.setText("rolls");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_rolls, gridBagConstraints);

        GUI_correct_label.setText("correct");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_correct_label, gridBagConstraints);

        GUI_correct.setEditable(false);
        GUI_correct.setText("correct");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_correct, gridBagConstraints);

        GUI_incorrect_label.setText("incorrect");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_incorrect_label, gridBagConstraints);

        GUI_incorrect.setEditable(false);
        GUI_incorrect.setText("incorrect");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_incorrect, gridBagConstraints);

        GUI_percentage_label.setText("percentage");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_percentage_label, gridBagConstraints);

        GUI_percentage.setEditable(false);
        GUI_percentage.setText("percentage");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(GUI_percentage, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GUI_roll_event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_roll_event
		GUI_roll_event();
    }//GEN-LAST:event_GUI_roll_event
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DiceGameWaterman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}// </editor-fold>// </editor-fold>// </editor-fold>// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DiceGameWaterman().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GUI_correct;
    private javax.swing.JLabel GUI_correct_label;
    private javax.swing.JTextField GUI_dice;
    private javax.swing.JLabel GUI_dice_label;
    private javax.swing.JSpinner GUI_guess;
    private javax.swing.JLabel GUI_guess_label;
    private javax.swing.JTextField GUI_incorrect;
    private javax.swing.JLabel GUI_incorrect_label;
    private javax.swing.JTextField GUI_percentage;
    private javax.swing.JLabel GUI_percentage_label;
    private javax.swing.JButton GUI_roll;
    private javax.swing.JTextField GUI_rolls;
    private javax.swing.JLabel GUI_rolls_label;
    private javax.swing.JLabel GUI_title;
    // End of variables declaration//GEN-END:variables
}
